version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb-auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_DATABASE: auth_db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
